<p style='margin:0cm;font-size:16px;font-family:"Times New Roman",serif;'><span style="font-size:15px;">Nomor &nbsp; &nbsp; &nbsp;: &nbsp;-</span></p>
<p style='margin:0cm;font-size:16px;font-family:"Times New Roman",serif;'><span style="font-size:15px;">Lampiran &nbsp;: &nbsp;-</span></p>
<p style='margin:0cm;font-size:16px;font-family:"Times New Roman",serif;'><span style="font-size:15px;">Hal &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; : &nbsp;Penelitian Bukti Pemenuhan Kewajiban Penyetoran Pajak</span></p>
<p style='margin:0cm;font-size:16px;font-family:"Times New Roman",serif;margin-left:2.0cm;'><span style="font-size:15px;">Penghasilan atas Penghasilan dari Pengalihan Hak atas Tanah</span></p>
<p style='margin:0cm;font-size:16px;font-family:"Times New Roman",serif;margin-left:2.0cm;'><span style="font-size:15px;">dan/atau Bangunan atau Perubahan Perjanjian Pengikatan</span></p>
<p style='margin:0cm;font-size:16px;font-family:"Times New Roman",serif;margin-left:2.0cm;'><span style="font-size:15px;">Jual Beli atas Tanah dan/atau Bangunan</span></p>
<p style='margin:0cm;font-size:16px;font-family:"Times New Roman",serif;margin-left:2.0cm;'><span style="font-size:15px;">&nbsp;</span></p>
<p style='margin:0cm;font-size:16px;font-family:"Times New Roman",serif;'><span style="font-size:15px;">Yth. Kepala Kantor Pelayanan Pajak</span></p>
<p style='margin:0cm;font-size:16px;font-family:"Times New Roman",serif;'><span style="font-size:15px;">Kota Banjarmasin</span></p>
<p style='margin:0cm;font-size:16px;font-family:"Times New Roman",serif;'><span style="font-size:15px;">di Tempat</span></p>
<p style='margin:0cm;font-size:16px;font-family:"Times New Roman",serif;'><span style="font-size:15px;">&nbsp;</span></p>
<p style='margin:0cm;font-size:16px;font-family:"Times New Roman",serif;'><span style="font-size:15px;">Saya yang bertanda tangan di bawah ini :&nbsp;</span></p>
<p style='margin:0cm;font-size:16px;font-family:"Times New Roman",serif;'><span style="font-size:15px;">Nama &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;: &nbsp;{{ $customer->where('ktp', $data->ktp_penjual)->pluck('nama')->implode('[]', '"') }}</span></p>
<p style='margin:0cm;font-size:16px;font-family:"Times New Roman",serif;'><span style="font-size:15px;">NPWP /NIK/Paspor &nbsp; : &nbsp;{{ $data->ktp_penjual }}</span></p>
<p style='margin:0cm;font-size:16px;font-family:"Times New Roman",serif;'><span style="font-size:15px;">Alamat &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;: &nbsp;{{ $customer->where('ktp', $data->ktp_penjual)->pluck('alamat')->implode('[]', '"') }}</span></p>
<p style='margin:0cm;font-size:16px;font-family:"Times New Roman",serif;'><span style="font-size:15px;">Telepon &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;: &nbsp;{{ $customer->where('ktp', $data->ktp_penjual)->pluck('telepon')->implode('[]', '"') }}</span></p>
<p style='margin:0cm;font-size:16px;font-family:"Times New Roman",serif;'><span style="font-size:15px;">dalam hal ini sebagai pihak yang mengalihkan tanah dan/ atau bangunan.</span></p>
<p style='margin:0cm;font-size:16px;font-family:"Times New Roman",serif;'><span style="font-size:15px;">&nbsp;</span></p>
<p style='margin:0cm;font-size:16px;font-family:"Times New Roman",serif;text-align:justify;'><span style="font-size:15px;">dengan ini mengajukan permohonan pembuktian pemenuhan kewajiban penyetoran pajak penghasilan atas penghasilan dari pengalihan hak atas tanah dan/atau bangunan <s>atau perubahan perjanjian pengikatan jual beli atas tanah dan/atau bangunan</s> melalui pelepasan hak tanpa hubungan istimewa<s>/jual beli dengan hubungan istimewa/tukar menukar/cara lain</s>**).</span></p>
<p style='margin:0cm;font-size:16px;font-family:"Times New Roman",serif;'><span style="font-size:15px;">&nbsp;Pengalihan sebagaimana dimaksud dilakukan kepada*):</span></p>
<p style='margin:0cm;font-size:16px;font-family:"Times New Roman",serif;'><span style="font-size:15px;">&nbsp;</span></p>
<p style='margin:0cm;font-size:16px;font-family:"Times New Roman",serif;'><span style="font-size:15px;"><span style='font-family: "MS Gothic";'>☐</span>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; a. Wajib Pajak atas pengalihan berupa Rumah Sederhana dan Rumah Susun Sederhana;</span></p>
<p style='margin:0cm;font-size:16px;font-family:"Times New Roman",serif;'><span style="font-size:15px;"><span style='font-family: "MS Gothic";'>☐</span>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; b. Special Purpose Company atau Kontrak Investasi Kolektif;</span></p>
<p style='margin:0cm;font-size:16px;font-family:"Times New Roman",serif;'><span style="font-size:15px;"><span style='font-family: "MS Gothic";'>☐</span>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; c. Selain butir a dan b;</span></p>
<p style='margin:0cm;font-size:16px;font-family:"Times New Roman",serif;'><span style="font-size:15px;">&nbsp;</span></p>
<p style='margin:0cm;font-size:16px;font-family:"Times New Roman",serif;'><span style="font-size:15px;">dengan keterangan objek pengalihan berupa tanah dan/atau bangunan sebagaimana terlampir.</span></p>
<p style='margin:0cm;font-size:16px;font-family:"Times New Roman",serif;'><span style="font-size:15px;">&nbsp;</span></p>
<p style='margin:0cm;font-size:16px;font-family:"Times New Roman",serif;text-align:justify;'><span style="font-size:15px;">Demikian surat permohonan ini kami sampaikan sesuai dengan keadaan yang sebenamya, apabila di kemudian hari diketahui bahwa temyata data-data yang disampaikan tidak benar dan/atau tidak sesuai dengan keadaan yang sebenamya, maka kami siap menerima segala konsekuensi sesuai dengan peraturan yang berlaku.</span></p>
<p style='margin:0cm;font-size:16px;font-family:"Times New Roman",serif;'><span style="font-size:15px;">&nbsp;</span></p>
<p style='margin:0cm;font-size:16px;font-family:"Times New Roman",serif;'><span style="font-size:15px;">Demikian disampaikan. &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Banjarmasin, {{ $date }}</span></p>
<p style='margin:0cm;font-size:16px;font-family:"Times New Roman",serif;'><span style="font-size:15px;">&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Wajib pajak,</span></p>
<p style='margin:0cm;font-size:16px;font-family:"Times New Roman",serif;'><span style="font-size:15px;">&nbsp;</span></p>
<p style='margin:0cm;font-size:16px;font-family:"Times New Roman",serif;'><span style="font-size:15px;">&nbsp;</span></p>
<p style='margin:0cm;font-size:16px;font-family:"Times New Roman",serif;'><span style="font-size:15px;">&nbsp;</span></p>
<p style='margin:0cm;font-size:16px;font-family:"Times New Roman",serif;'><span style="font-size:15px;">&nbsp;</span></p>
<p style='margin:0cm;font-size:16px;font-family:"Times New Roman",serif;'><span style="font-size:15px;">&nbsp;</span></p>
<p style='margin:0cm;font-size:16px;font-family:"Times New Roman",serif;'><span style="font-size:15px;">&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; {{ $customer->where('ktp', $data->ktp_penjual)->pluck('nama')->implode('[]', '"') }}</span></p>
